const itensLendarios = [
  { nome: "Abyssal Mask", tipo: ["tank"] },
  { nome: "Anathema's Chains", tipo: ["tank", "ad"] },
  { nome: "Dead Man's Plate", tipo: ["tank"] },
  { nome: "Force of Nature", tipo: ["tank"] },
  { nome: "Frozen Heart", tipo: ["tank"] },
  { nome: "Gargoyle Stoneplate", tipo: ["tank"] },
  { nome: "Hullbreaker", tipo: ["tank", "ad"] },
  { nome: "Knight's Vow", tipo: ["tank"] },
  { nome: "Randuin's Omen", tipo: ["tank"] },
  { nome: "Redemption", tipo: ["tank", "ap"] },
  { nome: "Silvermere Dawn", tipo: ["tank", "ad"] },
  { nome: "Spirit Visage", tipo: ["tank"] },
  { nome: "Sterak's Gage", tipo: ["tank", "ad"] },
  { nome: "Sunfire Aegis", tipo: ["tank"] },
  { nome: "Thornmail", tipo: ["tank"] },
  { nome: "Titanic Hydra", tipo: ["tank", "ad"] },
  { nome: "Turbo Chemtank", tipo: ["tank"] },
  { nome: "Vigilant Wardstone", tipo: ["tank", "ad", "ap"] },
  { nome: "Warmog's Armor", tipo: ["tank"] },
  { nome: "Winter's Approach", tipo: ["tank"] },
  { nome: "Zeke's Convergence", tipo: ["tank"] },
  { nome: "Archangel's Staff", tipo: ["ap"] },
  { nome: "Ardent Censer", tipo: ["ap"] },
  { nome: "Banshee's Veil", tipo: ["tank", "ap"] },
  { nome: "Chemtech Putrifier", tipo: ["ap"] },
  { nome: "Cosmic Drive", tipo: ["ap"] },
  { nome: "Demonic Embrace", tipo: ["ap"] },
  { nome: "Horizon Focus", tipo: ["ap"] },
  { nome: "Imperial Mandate", tipo: ["ap"] },
  { nome: "Lich Bane", tipo: ["ap", "ad"] },
  { nome: "Mejai's Soulstealer", tipo: ["ap"] },
  { nome: "Mikael's Blessing", tipo: ["ap"] },
  { nome: "Morellonomicon", tipo: ["ap"] },
  { nome: "Nashor's Tooth", tipo: ["ap", "ad"] },
  { nome: "Rabadon's Deathcap", tipo: ["ap"] },
  { nome: "Rylai's Crystal Scepter", tipo: ["ap"] },
  { nome: "Shadowflame", tipo: ["ap"] },
  { nome: "Staff of Flowing Water", tipo: ["ap"] },
  { nome: "Void Staff", tipo: ["ap"] },
  { nome: "Zhonya's Hourglass", tipo: ["ap", "ad", "tank"] },
  { nome: "Axiom Arc", tipo: ["ad"] },
  { nome: "Black Cleaver", tipo: ["ad", "tank"] },
  { nome: "Blade of the Ruined King", tipo: ["ad"] },
  { nome: "Bloodthirster", tipo: ["ad"] },
  { nome: "Chempunk Chainsword", tipo: ["ad", "tank"] },
  { nome: "Death's Dance", tipo: ["ad", "tank"] },
  { nome: "Edge of Night", tipo: ["ad"] },
  { nome: "Essence Reaver", tipo: ["ad"] },
  { nome: "Guardian Angel", tipo: ["ad", "tank"] },
  { nome: "Immortal Shieldbow", tipo: ["ad"] },
  { nome: "Kraken Slayer", tipo: ["ad"] },
  { nome: "Lord Dominik's Regards", tipo: ["ad"] },
  { nome: "Manamune", tipo: ["ad"] },
  { nome: "Maw of Malmortius", tipo: ["ad"] },
  { nome: "Mercurial Scimitar", tipo: ["ad"] },
  { nome: "Mortal Reminder", tipo: ["ad"] },
  { nome: "Phantom Dancer", tipo: ["ad"] },
  { nome: "Prowler's Claw", tipo: ["ad"] },
  { nome: "Rapid Firecannon", tipo: ["ad"] },
  { nome: "Ravenous Hydra", tipo: ["ad", "tank"] },
  { nome: "Runaan's Hurricane", tipo: ["ad"] },
  { nome: "Serpent's Fang", tipo: ["ad"] },
  { nome: "Serylda's Grudge", tipo: ["ad"] },
  { nome: "Spear of Shojin", tipo: ["ad"] },
  { nome: "Statikk Shiv", tipo: ["ad"] },
  { nome: "Stormrazor", tipo: ["ad"] },
  { nome: "The Collector", tipo: ["ad", "tank", "ap"] },
  { nome: "Umbral Glaive", tipo: ["ad"] },
  { nome: "Wit's End", tipo: ["ad", "tank"] },
];
